# Docker-specific routes using Service Discovery
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**
spring.cloud.gateway.routes[0].filters[0].name=AuthenticationFilter

spring.cloud.gateway.routes[1].id=policy-service
spring.cloud.gateway.routes[1].uri=lb://policy-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/policies/**
spring.cloud.gateway.routes[1].filters[0].name=AuthenticationFilter

spring.cloud.gateway.routes[2].id=claims-service
spring.cloud.gateway.routes[2].uri=lb://claims-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/claims/**
spring.cloud.gateway.routes[2].filters[0].name=AuthenticationFilter

spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=lb://admin-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/admin/**
spring.cloud.gateway.routes[3].filters[0].name=AuthenticationFilter

# Others
spring.cloud.gateway.routes[4].id=config-server
spring.cloud.gateway.routes[4].uri=http://config-server:8888
spring.cloud.gateway.routes[4].predicates[0]=Path=/config/**

spring.cloud.gateway.routes[5].id=service-registry
spring.cloud.gateway.routes[5].uri=http://service-registry:8761
spring.cloud.gateway.routes[5].predicates[0]=Path=/eureka/**

eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
