sonar.projectKey=smartsure-insurance-management
sonar.projectName=SmartSure Insurance Management System
sonar.host.url=http://localhost:9000
sonar.token=sqa_f5f4ebc148e18a33ba08ebb2548515e1c8819b81

# Module definitions
sonar.modules=auth-service,policy-service,claims-service,admin-service,api-gateway

# Module source configurations
auth-service.sonar.projectBaseDir=auth-service
auth-service.sonar.sources=src/main/java
auth-service.sonar.tests=src/test/java
auth-service.sonar.java.binaries=target/classes
auth-service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

policy-service.sonar.projectBaseDir=policy-service
policy-service.sonar.sources=src/main/java
policy-service.sonar.tests=src/test/java
policy-service.sonar.java.binaries=target/classes
policy-service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

claims-service.sonar.projectBaseDir=claims-service
claims-service.sonar.sources=src/main/java
claims-service.sonar.tests=src/test/java
claims-service.sonar.java.binaries=target/classes
claims-service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

admin-service.sonar.projectBaseDir=admin-service
admin-service.sonar.sources=src/main/java
admin-service.sonar.tests=src/test/java
admin-service.sonar.java.binaries=target/classes
admin-service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

api-gateway.sonar.projectBaseDir=api-gateway
api-gateway.sonar.sources=src/main/java
api-gateway.sonar.tests=src/test/java
api-gateway.sonar.java.binaries=target/classes
api-gateway.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Language and encoding
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.coveragePlugin=jacoco
